---
'_AnimalExtract_import_cols':
    - "ACCOUNT__C"
    - "ADOPTED__C"
    - "ADOPTION_FEE_PAID__C"
    - "ADOPTION_PHASE__C"
    - "AGE_INDICATOR__C"
    - "AGE__C"
    - "ATTITUDE_TOWARDS_PETS__C"
    - "ATTITUDES_TOWARDS_KIDS__C"
    - "BIRTHDATE__C"
    - "COLOR_PATTERN__C"
    - "CREATEDDATE"
    - "DECLAWED_ALL_4__C"
    - "DECLAWED__C"
    - "DOCKED_TAIL__C"
    - "EARS_CROPPED_TIPPED__C"
    - "GENDER__C"
    - "GENERAL_CONDITION__C"
    - "HOUSETRAINED__C"
    - "HOUSETRAINING_NOTES__C"
    - "ID"
    - "IMAGE__C"
    - "LIVED_WITH_PETS__C"
    - "LIVED_WTIH_KIDS__C"
    - "MICROCHIP_DATE_ISSUED__C"
    - "NAME"
    - "ON_HOLD_UNTIL__C"
    - "OVERALL_HEALTH_NOTES__C"
    - "PRIMARY_BREED__C"
    - "PRIMARY_COLOR__C"
    - "RABIES_EXPIRATION__C"
    - "RESTRICTIONS_NOTES__C"
    - "RESTRICTIONS__C"
    - "SECONDARY_BREED__C"
    - "SECONDARY_COLOR__C"
    - "SIZE_AT_MATURITY__C"
    - "SPAYED_NEUTERED__C"
    - "SPECIES__C"
    - "WEIGHT__C"

'_AnimalExtract_rename_dict':
    'ACCOUNT__C': "account_id"
    'ADOPTED__C': "adopted_ind"
    'ADOPTION_FEE_PAID__C': "adoption_fee_paid_ind"
    'ADOPTION_PHASE__C': "adoption_phase"
    'AGE_INDICATOR__C': "age_units"
    'AGE__C': "age"
    'ATTITUDE_TOWARDS_PETS__C': "attitude_pets"
    'ATTITUDES_TOWARDS_KIDS__C': "attitude_kids"
    'BIRTHDATE__C': "birthdate"
    'COLOR_PATTERN__C': "color_pattern"
    'CREATEDDATE': "animal_record_create_date"
    'DECLAWED_ALL_4__C': "declawed_all_ind"
    'DECLAWED__C': "declawed_ind"
    'DOCKED_TAIL__C': "docked_tail_ind"
    'EARS_CROPPED_TIPPED__C': "ears_cropped_ind"
    'GENDER__C': "gender"
    'GENERAL_CONDITION__C': "general_condition"
    'HOUSETRAINED__C': "housetrained_lbl"
    'HOUSETRAINING_NOTES__C': "housetrained_notes"
    'ID': "animal_id"
    'IMAGE__C': "image_url"
    'LIVED_WITH_PETS__C': "lived_w_pets_lbl"
    'LIVED_WTIH_KIDS__C': "lived_w_kids_lbl"
    'MICROCHIP_DATE_ISSUED__C': "chip_issue_date"
    'NAME': "animal_name"
    'ON_HOLD_UNTIL__C': "on_hold_until_date"
    'OVERALL_HEALTH_NOTES__C': "overall_health_notes"
    'PRIMARY_BREED__C': "primary_breed"
    'PRIMARY_COLOR__C': "primary_color"
    'RABIES_EXPIRATION__C': "rabies_exp_date"
    'RESTRICTIONS_NOTES__C': "adoption_restriction_notes"
    'RESTRICTIONS__C': "adoption_restriction_lbl"
    'SECONDARY_BREED__C': "secondary_breed"
    'SECONDARY_COLOR__C': "secondary_color"
    'SIZE_AT_MATURITY__C': "size_at_maturity"
    'SPAYED_NEUTERED__C': "spay_neuter_ind"
    'SPECIES__C': "species"
    'WEIGHT__C': "weight"

_AnimalExtract_dtypes:
    ACCOUNT__C: object
    ADOPTED__C: bool
    ADOPTION_FEE_PAID__C: bool
    ADOPTION_PHASE__C: object
    AGE_INDICATOR__C: object
    AGE__C: object
    ATTITUDE_TOWARDS_PETS__C: object
    ATTITUDES_TOWARDS_KIDS__C: object
    BIRTHDATE__C: datetime64
    COLOR_PATTERN__C: object
    CREATEDDATE: datetime64
    DECLAWED_ALL_4__C: bool
    DECLAWED__C: bool
    DOCKED_TAIL__C: bool
    EARS_CROPPED_TIPPED__C: bool
    GENDER__C: object
    GENERAL_CONDITION__C: object
    HOUSETRAINED__C: object
    HOUSETRAINING_NOTES__C: object
    ID: object
    IMAGE__C: object
    LIVED_WITH_PETS__C: object
    LIVED_WTIH_KIDS__C: object
    MICROCHIP_DATE_ISSUED__C: object
    NAME: object
    ON_HOLD_UNTIL__C: datetime64
    OVERALL_HEALTH_NOTES__C: object
    PRIMARY_BREED__C: object
    PRIMARY_COLOR__C: object
    RABIES_EXPIRATION__C: object
    RESTRICTIONS_NOTES__C: object
    RESTRICTIONS__C: object
    SECONDARY_BREED__C: object
    SECONDARY_COLOR__C: object
    SIZE_AT_MATURITY__C: object
    SPAYED_NEUTERED__C: bool
    SPECIES__C: object
    WEIGHT__C: float64
